---
- name: install Grafana
  hosts: main
  become: yes

  tasks:
  - name: Delete Apt Key
    ansible.builtin.apt_key:
      id: SOME_ID # ADD THE INSTANCE ID FROM THE INSTALLATION
      state: absent
  - name: Remove grafana.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: absent
  - name: Ensure Grafana is stopped and disabled
    ansible.builtin.service:
      name: grafana-server
      enabled: no
      state: stopped
  - name: Remove Grafana
    ansible.builtin.apt:
      name: grafana
      state: absent